[tool.poetry]
name = "temporian"
version = "0.1.0"
description = ""
authors = [
    "Guillermo Etchebarne <getchebarne@tryolabs.com>",
    "Ian Spektor <ispektor@tryolabs.com>",
    "Mathieu Guillame-Bert <gbm@google.com>",
    "Richard Stotz <richardstotz@google.com>"
]

[tool.poetry.dependencies]
python = "^3.9,<3.11"
absl-py = "^1.3.0"
protobuf = "^4.21.12"
pandas = "^1.5.2"
matplotlib = "^3.7.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
toml = "^0.10.2"
pylint = "^2.15.10"
memory-profiler = "^0.61.0"
scalene = "^1.5.20"

[tool.black]
line-length = 80
preview = true

[tool.pylint]
max-line-length = 80

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
