# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Poetry usage based on:
#   https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "16"
  apt_packages:
    - rsync
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - npm install -g @bazel/bazelisk

    post_install:
      - poetry install

    pre_build:
      - tools/run_notebooks.sh

mkdocs:
  configuration: docs/mkdocs.yml
