# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  apt_packages:
    - pipx
  tools:
    python: "3.10"
  commands:
    - pipx install poetry
    - pipx ensurepath
    - poetry install --no-interaction
    - poetry run python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file docs/mkdocs.yml
