site_name: Temporian
site_url: https://temporian.readthedocs.io/en/stable/
repo_url: https://github.com/google/temporian

# Theme
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.indexes
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: white
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: white

# Root dir for docs source
docs_dir: src

# Extra CSS
extra_css:
  # TODO: continue working on this css customization for temporian
  - css/custom.css

# Navigation bar
nav:
  - Home: index.md
  - 3 minutes to Temporian: 3_minutes.md
  - User Guide: user_guide.md
  - Tutorials: tutorials/
  - API Reference: reference/ # generated by gen-files + literate-nav

# Plugins
plugins:
  - search
  - exclude-search:
      # Exclude all files not listed in the nav section nor referenced by other files.
      exclude_unreferenced: true
  - autorefs
  - gen-files:
      scripts:
        # Generate the index page from the README.md.
        - gen_index.py
        # Generate the reference pages from docstrings.
        - gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocs-jupyter:
      # Execute notebooks when building docs (set to true when temporian runs in a notebook w/o the start_notebook script).
      execute: false
      include: ["*.ipynb"] # Use ["*.py", "*.ipynb"] to render jupytext too.
      allow_errors: false # Cancel build if cell execution fails.
      theme: dark
  # Configuration to generate the reference pages from the docstrings.
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            # https://mkdocstrings.github.io/python/usage/#globallocal-options
            docstring_style: google
            heading_level: 1
            members_order: source
            show_source: false
            show_submodules: false
            merge_init_into_class: false
            show_signature: true
            separate_signature: true
            show_signature_annotations: true
            show_if_no_docstring: false
            group_by_category: true
            show_category_heading: false
            show_root_heading: true
            # show_root_toc_entry: false
            # show_symbol_type_heading: false
            # preload_modules: [temporian.core.operators]
            # allow_inspection: true

# Customization for Markdown
markdown_extensions:
  - toc:
      permalink: "#" # custom symbol at the end of each headline
  - pymdownx.details # call-outs collapsible
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences # arbitrary nesting of code and content blocks inside each other.
  - pymdownx.snippets: # to embed content from arbitrary files into a document
      check_paths: true
  - pymdownx.tabbed: # add support for tabs using ===
      alternate_style: true
  - pymdownx.superfences: # to render mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

watch:
  - ../README.md
  - ../temporian
  - ./gen_ref_pages.py
  - ./gen_index.py
