name: publish-macos

# TODO: change to either only run on release branch or on tags/releases
on:
  push:
    branches:
      - publish-action

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build package
        run: poetry build

      - name: Save package for following jobs
        uses: actions/upload-artifact@v3
        with:
          name: dist-macos-${{ matrix.python-version }}
          path: dist

  test-install-macos:
    needs: [build-macos]
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: dist-macos-${{ matrix.python-version }}
          path: dist

      - name: Install from wheel
        run: pip install dist/*.whl

      - name: Test installation
        run: python ./tools/check_install.py

  publish-macos:
    needs: [test-install-macos]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Download builds for all Python versions
        uses: actions/download-artifact@v3
        with:
          # Skipping name: key to download all artifacts from this workflow
          # Artifacts are are downloaded to dist/<artifact-name>
          path: dist

      - name: Move wheels and sources to dist/
        run: |
          mv dist/*/*.whl dist/
          mv -f dist/*/*.tar.gz dist/

      - name: Publish to PyPI
        # TODO: change to prod PyPI, and prod token in repo's secrets
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
          poetry publish -r test-pypi -n
