name: publish-macos

# TODO: change to only run on release branch
on:
  push:
    branches:
      - publish-action

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: gcr.io/tfx-oss-public/manylinux2014-bazel:bazel-5.3.0
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build package
        run: |
          version="${{ matrix.python-version }}"
          versionstr=${version//./}
          PYTHON_VERSION=$versionstr ./tools/build_manylinux.sh

      - name: Save package for following jobs
        uses: actions/upload-artifact@v3
        with:
          name: dist-ubuntu-${{ matrix.python-version }}
          path: dist

  build-macos:
    runs-on: macos-latest-xl
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build package
        run: poetry build

      - name: Save package for following jobs
        uses: actions/upload-artifact@v3
        with:
          name: dist-macos-${{ matrix.python-version }}
          path: dist

  test-install:
    needs: [build-linux, build-macos]
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        platform: ["ubuntu", "macos"]
    runs-on: ${{ matrix.platform }}-latest
    # Workaround for macos pip compatibility issue
    # See https://github.com/actions/setup-python/issues/469
    env:
      SYSTEM_VERSION_COMPAT: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: dist-${{ matrix.platform }}-${{ matrix.python-version }}
          path: dist

      - name: Install from wheel
        run: pip install dist/*.whl

      - name: Test installation
        run: python tools/check_install.py

  publish:
    needs: [test-install]
    runs-on: ubuntu-latest
    # TODO: change to production-pypi
    environment: test-pypi
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Download builds for all Python versions and platforms
        uses: actions/download-artifact@v3
        with:
          # Skipping `name` key to download all artifacts from this workflow
          # Artifacts are are downloaded to dist/<artifact-name>
          path: dist

      - name: Move wheels and sources to dist/
        run: |
          mv dist/*/*.whl dist/
          mv -n dist/*/*.tar.gz dist/

      - name: Publish to PyPI
        # TODO: change to prod PyPI, and prod token in repo's secrets
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish -r test-pypi --no-interaction --skip-existing
